<a href="https://colab.research.google.com/github/Poorni2415/ML-projects/blob/main/Standardization_and_label_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [ ]:
c=pd.read_csv('/content/data.csv')
i=pd.read_csv('/content/iris_data.csv')

In [ ]:
c.head()

id diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst  Unnamed: 32
0    842302         M        17.99  ...          0.4601                  0.11890          NaN
1    842517         M        20.57  ...          0.2750                  0.08902          NaN
2  84300903         M        19.69  ...          0.3613                  0.08758          NaN
3  84348301         M        11.42  ...          0.6638                  0.17300          NaN
4  84358402         M        20.29  ...          0.2364                  0.07678          NaN

[5 rows x 33 columns]

In [ ]:
c.shape

(569, 33)

In [ ]:
c['diagnosis'].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [ ]:
e=LabelEncoder()

In [ ]:
s=e.fit_transform(c.diagnosis)

In [ ]:
c['Target']=s

In [ ]:
c.head()

id diagnosis  radius_mean  ...  fractal_dimension_worst  Unnamed: 32  Target
0    842302         M        17.99  ...                  0.11890          NaN       1
1    842517         M        20.57  ...                  0.08902          NaN       1
2  84300903         M        19.69  ...                  0.08758          NaN       1
3  84348301         M        11.42  ...                  0.17300          NaN       1
4  84358402         M        20.29  ...                  0.07678          NaN       1

[5 rows x 34 columns]

In [ ]:
c['Target'].value_counts()

Target
0    357
1    212
Name: count, dtype: int64

In [ ]:
d=e.fit_transform(i.Species)

In [ ]:
i.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
i['Species'].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [ ]:
i['Tar']=d

In [ ]:
i.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species  Tar
0   1            5.1           3.5            1.4           0.2  Iris-setosa    0
1   2            4.9           3.0            1.4           0.2  Iris-setosa    0
2   3            4.7           3.2            1.3           0.2  Iris-setosa    0
3   4            4.6           3.1            1.5           0.2  Iris-setosa    0
4   5            5.0           3.6            1.4           0.2  Iris-setosa    0

In [ ]:
i['Tar'].value_counts()

Tar
0    50
1    50
2    50
Name: count, dtype: int64

In [ ]:
i.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species  Tar
145  146            6.7           3.0            5.2           2.3  Iris-virginica    2
146  147            6.3           2.5            5.0           1.9  Iris-virginica    2
147  148            6.5           3.0            5.2           2.0  Iris-virginica    2
148  149            6.2           3.4            5.4           2.3  Iris-virginica    2
149  150            5.9           3.0            5.1           1.8  Iris-virginica    2

In [ ]:
b=pd.read_csv('/content/diabetes.csv')

In [ ]:
b.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  ...   BMI  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72             35  ...  33.6                     0.627   50        1
1            1       85             66             29  ...  26.6                     0.351   31        0
2            8      183             64              0  ...  23.3                     0.672   32        1
3            1       89             66             23  ...  28.1                     0.167   21        0
4            0      137             40             35  ...  43.1                     2.288   33        1

[5 rows x 9 columns]

In [ ]:
b.shape

(768, 9)

In [ ]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [ ]:
X=b.drop(columns='Outcome',axis=1)
Y=b['Outcome']

In [ ]:
print(X)

     Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
0              6      148             72  ...  33.6                     0.627   50
1              1       85             66  ...  26.6                     0.351   31
2              8      183             64  ...  23.3                     0.672   32
3              1       89             66  ...  28.1                     0.167   21
4              0      137             40  ...  43.1                     2.288   33
..           ...      ...            ...  ...   ...                       ...  ...
763           10      101             76  ...  32.9                     0.171   63
764            2      122             70  ...  36.8                     0.340   27
765            5      121             72  ...  26.2                     0.245   30
766            1      126             60  ...  30.1                     0.349   47
767            1       93             70  ...  30.4                     0.315   23

[76

In [ ]:
print(Y)

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64


In [ ]:
print(b)

     Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0              6      148             72  ...                     0.627   50        1
1              1       85             66  ...                     0.351   31        0
2              8      183             64  ...                     0.672   32        1
3              1       89             66  ...                     0.167   21        0
4              0      137             40  ...                     2.288   33        1
..           ...      ...            ...  ...                       ...  ...      ...
763           10      101             76  ...                     0.171   63        0
764            2      122             70  ...                     0.340   27        0
765            5      121             72  ...                     0.245   30        0
766            1      126             60  ...                     0.349   47        1
767            1       93             70  ...         

In [ ]:
s=StandardScaler()
n=s.fit_transform(X)

In [ ]:
n

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [ ]:
X=n
Y=b['Outcome']

## Splitting the Data

In [ ]:
X_Train,X_Test,Y_Train,Y_Test= train_test_split(X,Y,test_size=0.3,random_state=4)

In [ ]:
X_Train

array([[ 0.04601433, -0.81042491,  0.04624525, ...,  0.0136339 ,
         0.4231902 , -0.78628618],
       [-1.14185152, -0.05929342, -3.57259724, ...,  0.05170968,
        -0.9992857 , -0.78628618],
       [-0.54791859, -0.65393918,  0.04624525, ...,  1.07975556,
         0.61949791, -0.70119842],
       ...,
       [ 0.63994726, -0.43485916,  0.97680475, ...,  0.61015436,
         0.77050385, -0.19067191],
       [-0.54791859, -1.43636781, -0.26394125, ..., -0.29097229,
        -0.30767852, -0.0204964 ],
       [-0.54791859, -0.43485916,  0.25303625, ...,  0.20401277,
        -0.20499449, -0.87137393]])

In [ ]:
X_Train.shape

(537, 8)

In [ ]:
X_Test

array([[-8.44885053e-01, -6.53939181e-01, -1.60545747e-01, ...,
         9.41978774e-04, -8.41897406e-02,  7.45293379e-01],
       [ 1.53084665e+00, -1.99971643e+00,  5.63222752e-01, ...,
         1.02477375e-01, -1.13519104e+00,  6.60205626e-01],
       [-1.14185152e+00, -6.53939181e-01,  4.62452528e-02, ...,
        -1.51361116e-01,  3.77888417e-01, -1.04154944e+00],
       ...,
       [-2.50952128e-01,  2.84975179e-01,  4.59827252e-01, ...,
        -4.55967305e-01, -4.49624101e-01,  6.45913543e-02],
       [-1.14185152e+00, -8.10424908e-01, -2.63941247e-01, ...,
         1.60012447e+00, -3.19758997e-01, -9.56461683e-01],
       [-2.50952128e-01, -1.53184856e-01, -3.57259724e+00, ...,
        -1.07787161e+00, -8.60360241e-01, -8.71373930e-01]])

In [ ]:
X_Test.shape

(231, 8)

In [ ]:
X

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [ ]:
X.shape

(768, 8)

In [ ]:
Y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [ ]:
Y_Train

262    0
619    1
275    0
338    1
177    1
      ..
360    1
709    1
439    0
174    0
122    0
Name: Outcome, Length: 537, dtype: int64

In [ ]:
Y_Test

390    0
146    0
136    0
420    0
328    1
      ..
647    1
216    1
730    1
682    0
347    0
Name: Outcome, Length: 231, dtype: int64

In [ ]:
c=pd.read_csv('/content/credit_data.csv')

In [ ]:
c.tail()

Time        V1        V2        V3        V4  ...       V26       V27       V28  Amount  Class
11954  20631  1.504204 -0.411728  0.200090 -0.778753  ... -0.235062 -0.012089  0.000905    9.00    0.0
11955  20636  1.134994  0.096340  0.277921  0.319692  ...  0.279049  0.012398 -0.009090    0.99    0.0
11956  20638 -6.305012  3.944886 -4.707362  1.539602  ... -0.447540  0.212900 -0.031021   89.99    0.0
11957  20638  1.161960 -0.398297  1.123732 -0.474237  ... -0.712765  0.073836  0.028055   11.85    0.0
11958  20642  1.291096 -0.226628  0.708386 -0.719236  ...       NaN       NaN       NaN     NaN    NaN

[5 rows x 31 columns]

In [ ]:
c['Class'].value_counts()

Class
0.0    11906
1.0       52
Name: count, dtype: int64

In [ ]:
X=c[c.Class==0.0]
Y=c[c.Class==1.0]

In [ ]:
Z=X.sample(n=52)

In [ ]:
Z.shape

(52, 31)

In [ ]:
Y.shape

(52, 31)

In [ ]:
nd=pd.concat([Z,Y],axis=0)

In [ ]:
nd.tail()

Time         V1        V2         V3  ...       V27       V28  Amount  Class
10897  18690 -15.398845  7.472324 -19.026912  ...  2.262942 -1.178063     1.0    1.0
11343  19762 -14.179165  7.421370 -21.405836  ...  2.171905 -1.395288     1.0    1.0
11710  20011 -14.724627  7.875157 -21.872317  ...  2.161129 -1.401282     1.0    1.0
11841  20332 -15.271362  8.326581 -22.338591  ...  2.149247 -1.406811     1.0    1.0
11880  20451 -15.819179  8.775997 -22.804686  ...  2.136424 -1.411945     1.0    1.0

[5 rows x 31 columns]

In [ ]:
nd.head()

Time        V1        V2        V3        V4  ...       V26       V27       V28  Amount  Class
6816   8599  1.320528  0.071856  0.174214 -0.171412  ...  0.956847 -0.116417 -0.022166    0.77    0.0
6065   6877  1.187374 -0.538202  0.501987 -0.085761  ...  1.021768 -0.060499 -0.018922   40.78    0.0
8846  12098 -0.322432  1.098045  1.532224  0.287641  ...  0.172655  0.145697 -0.014951    3.13    0.0
2686   2226 -0.473552  0.630082  1.457909 -0.180220  ...  0.025537  0.135824  0.143960    7.49    0.0
7079   9276 -1.042314 -0.840181  1.662427  0.485675  ...  0.146621  0.136415  0.245658    0.01    0.0

[5 rows x 31 columns]

In [ ]:
nd.shape

(104, 31)

In [ ]:
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
e=pd.read_csv('/content/train.csv')

ParserError: Error tokenizing data. C error: EOF inside string starting at row 7758